# References {#references}

This reference list is divided by each of the user guide’s chapters along with subheaders for the connecting theme between each group of citations. I decided to order each cluster descending by year since NLP is a rapidly growing discipline and starting with older works will likely aid reader’s understanding of newer innovations. The featured references undeniably reflect my own disciplinary training biases in sociology & information science, but I think social scientists outside of either of those specific disciplines can still gain much from the included papers.

I purposely tried to highlight Cornell scholars and researchers throughout the sections. There’s no way I could include the sheer variety of research without this list becoming massive, so consider this to be a further reading “launch pad” aligned with the introduced topics in the user guide that you can then expand on further within your own literature reviews. 

## Chapter 1- Introduction

### Data and the Information Age
* Golder, Scott and Michael Macy. 2014. “Digital Footprints: Opportunities and Challenges for Online Social Research.” *Annual Review of Sociology* 40: 129-152.
* Salganik, Matthew. 2018. *Bit by Bit: Social Research in the Digital Age.* Princeton, NJ: Princeton University Press. 
* Brady, Henry E. 2019. “The Challenges of Big Data and Data Science.” *Annual Review of Political Science* 22: 297-323. 
* Hargittai, Eszter. 2020. “Potential Biases in Big Data: Omitted Voices on Social Media.” *Social Science Computer Review* 38(1): 10-24. 

### CSS and NLP
* DiMaggio, Paul. 2015. “Adapting Computational Text Analysis to Social Science (and Vice Versa).” *Big Data & Society* 2(2): 1-5.
* Evans, James A. and Pedro Aceves. 2016. “Machine Translation: Mining Text for Social Theory.” *Annual Review of Sociology* 42: 21-50. 
* Nelson, Laura K. 2017. “Computational Grounded Theory: A Methodological Framework.” *Sociological Methods & Research* 49(1): 3-42. 
* Wallach, Hanna. 2018. “Computational Social Science ≠ Computer Science + Social Data.” *Communications of the ACM* 61(3): 42-44.
* Lazer et al. 2020. "Computational Social Science: Obstacles and Opportunities.” *Science* 369(6507): 1060-1062.
* Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. 2021. *Text as Data: A New Framework for Machine Learning and the Social Sciences.* Princeton, NJ: Princeton University Press. 

### NLP Resources Specific to R Applications
* Silge, Julia, and David Robinson. 2017. *Text Mining with R: A Tidy Approach.* Newton, MA: O’Reilly Media
* Jockers, Matthew L. and Rosamond Thalken. 2020. *Text Analysis with R*. New York, NY: Springer. 
* Hvitfeldt, Emil and Julia Silge. 2021. *Supervised Machine Learning for Text Analysis in R.* Boca Raton, Florida: CRC Press. 

## Chapter 2- Text Preprocessing 

### Text Preprocessing
* Helpful blog post on encodings- https://kunststube.net/encoding/
* Uysal, A. K., and Gunal, S. 2014. "The Impact of Preprocessing on Text Classification." *Information Processing & Management* 50(1), 104-112.
* Denny, M. J., and Spirling, A. 2018. “Text Preprocessing For Unsupervised Learning: Why It Matters, When It Misleads, And What To Do About It.” *Political Analysis* 26(2): 168–189.
* Hickman, Louis, Stuti Thapa, … et al. 2020. “Text Preprocessing for Text Mining in Organizational Research: Review and Recommendations.” *Organizational Research Methods*: 1-33. 
* Great website to learn regexes- https://www.regular-expressions.info/

### Stemming, Stopwords, and Parts of Speech
* Derczynski, Leon, Alan Ritter, Sam Clark, and Kalina Bontcheva. 2013. “Twitter Part-of-Speech Tagging for All: Overcoming Sparse and Noisy Data.” *Proceedings of Recent Advances in Natural Language Processing*: 198-206. 
* Tsuboi, Yuta. 2014. “Neural Networks Leverage Corpus-wide Information for Part-of-Speech Tagging.” *Proceedings of the 2014 Conference on Empirical Methods in Natural Language Processing*: 938-950. 
* Schofield, A., and Mimno, D. 2016. “Comparing Apples to Apple: The Effects of Stemmers on Topic Models.” *TACL* 4(2): 287–300.
* Singh, Jasmeet and Vishal Gupta. 2017. “A Systematic Review of Text Stemming Techniques.” *Artificial Intelligence Review* 48: 157-217. 
* Schofield, Alexandra, Måns Magnusson, and David Mimno. 2017. “Pulling Out the Stops: Rethinking Stopword Removal for Topic Models.” *Proceedings of the 15th Conference of the European Chapter of the Association for Computational Linguistics*: 432-436. 

## Chapter 3 – Dictionaries & Sentiment Analysis

### Counts & Dictionary Based Studies
* Monroe, Burt, Michael Colaresi, and Kevin Quinn. 2008. “Fightin’ Words: Lexical Feature Selection and Evaluation for Identifying the Content of Political Conflict.” *Political Analysis* 16(4): 372-403.
* Loughran, Tim and Bill McDonald. 2011. “When Is a Liability Not a Liability? Textual Analysis, Dictionaries, and 10-Ks” *The Journal of Finance* 66(1): 35-65. 
* Sap, Maarten, Marcella Cindy Prasetio, Ari Holtzman, Hannah Rashkin, and Yejin Choi. 2017. “Connotation Frames of Power and Agency in Modern Films.” *Proceedings of the 2017 Conference on Empirical Methods in Natural Language Processing (EMNLP)*: 2329-2334. 
* Antoniak, Maria and David Mimno. 2021. “Bad Seeds: Evaluating Lexical Methods for Bias Measurement.” *Proceedings of the 59th Annual Meeting of the Association for Computational Linguistics and the 11th International Joint Conference on Natural Language Processing*: 1889-1904.

### LIWC
* Tausczik, Yla R., and James W. Pennebaker. 2010. ”The Psychological Meaning of Words: LIWC and Computerized Text Analysis Methods.” *Journal of Language and Social Psychology* 29(1): 24-54.
* Bulkeley, Kelly and Mark Graves. 2018. “Using the LIWC program to study dreams.” *Dreaming* 28(1): 43–58.
* Sergent, Kayla and Alexander D. Stajkovic. 2020. “Women’s Leadership is Associated with Fewer Deaths During the COVID-19 Crisis: Quantitative and Qualitative Analyses of United States Governors.” *Journal of Applied Psychology* 105(8): 771-783. 
* Yin, Dezhi, Samuel D. Bond, and Han Zhang. 2021. “Anxious or Angry? Effects of Discrete Emotions on the Perceived Helpfulness of Online Reviews.” *MIS Quarterly* 38(2): 539-560.

### Sentiment Analysis
* Pang, Bo, and Lillian Lee. 2008. “Opinion Mining and Sentiment Analysis.” *Foundations and Trends in Information Retrieval* 2(1–2): 1–135.
* Bao, Yanwei, Changqin Qian, Lijuan Wang, and Fuji Ren. 2014. “The Role of Pre-Processing in Twitter Sentiment Analysis.” *International Conference on Intelligent Computing*: 615-624. 
* Chauhan, Priyavrat, Nonita Sharma, and Geeta Sikka. 2021. “The Emergence of Social Media Data and Sentiment Analysis in Election Prediction.” *Journal of Ambient Intelligence and Humanized Computing* 12: 2601-2627. 

### VADER
* O’Connor, Brendan, Ramnath Balasubramanyan, Bryan R. Routledge, and Noah A. Smith. 2010. “From Tweets to Polls: Linking Text Sentiment to Public Opinion Time Series.” *Proceedings of the International AAAI Conference on Weblogs and Social Media (ICWSM)*: 122-129. 
* Hutto, C.J. and Eric Gilbert. 2014. “VADER: A Parsimonious Rule-based Model for Sentiment Analysis of Social Media Text.” *Proceedings of the Eighth International AAAI Conference on Weblogs and Social Media*: 216-225. 
* Kim, Young Bin, Jun Gi Kim, … et al. 2016. “Predicting Fluctuations in Cryptocurrency Transactions Based on User Comments and Replies.” *PLOS ONE* 11(8): 1-17. 
* Kumar, Srijan, William L. Hamilton, Jure Leskovec, and Dan Jurafsky. 2018. “Community Interaction and Conflict on the Web” *WWW*: 933-943. 

### Alternative Sentiment Analysis Approaches
* Soleymani, Mohammad, David Garcia, … et al. 2017. “A Survey of Multimodal Sentiment Analysis.” *Image and Vision Computing* 65: 3-14. 
* Hemmatian, Fatemeh and Mohammad Karim Sohrabi. 2019. “A Survey on Classification Techniques for Opinion Mining and Sentiment Analysis.” *Artificial Intelligence Review* 52: 1495-1545. 
* Yadav, Ashima and Dinesh Kumar Vishwakarma. 2019. “Sentiment Analysis Using Deep Learning Architectures: A Review.” *Artificial Intelligence Review* 53: 4335-4385. 

## Chapter 4- Machine Learning & Topic Models 

### Machine Learning for Social Science Annual Reviews
* Molina, Mario and Filiz Garip. 2019. “Machine Learning for Sociology.” *Annual Review of Sociology* 45: 27-45. 
* Athey, Susan and Guido W. Imbens. 2019. “Machine Learning Methods That Economists Should Know About.” *Annual Review of Economics* 11: 685-725.
* Orrù, Graziella, Merylin Monaro, … et al. 2020. “Machine Learning in Psychometrics and Psychological Research.” *Frontiers in Psychology* 10(2970): 1-10. 
* Grimmer, Justin, Margaret E. Roberts, and Brandon M. Stewart. 2021. “Machine Learning for Social Science: An Agnostic Approach.” *Annual Review of Political Science* 24: 395-419. 


### Topic Model Papers
* Chang, Jonathan, Jordan Boyd-Graber, Sean Gerrish, Chong Wang, and David M. Blei. 2009. “Reading Tea Leaves: How Humans Interpret Topic Models.” *Advances in Neural Information Processing Systems* 22: 1-9. 
* Blei, David. 2012. “Probabilistic Topic Models.” *Communications of the ACM* 55 (4): 77-84.
* Mohr, John, and Petko Bogdanov. 2013. “Introduction—Topic Models: What They Are and Why They Matter.” *Poetics* 41 (6): 545–69. 
* Baumer, Erin P.S., David Mimno, Shion Guha, Emily Quan, and Geri K. Gay. 2017. “Comparing Grounded Theory and Topic Modeling: Extreme Divergence or Unlikely Convergence?” *Journal of the Association for Information Science and Technology* 68(6): 1397-1410.

### Structural Topic Models Author Papers
* Check out the structural topic model website for an extensive list of studies that have used STMs - https://www.structuraltopicmodel.com/
* Roberts, Stewart, Tingley, Lucas, Leder-Luis, Gadarian, Albertson, and Rand. 2014. "Structural Topic Models for Open-Ended Survey Responses." *American Journal of Political Science* 58(4): 1064-1082. 
* Roberts, Margaret, Brandon Stewart, and Dustin Tingley. 2019. “stm: A Package for Structural Topic Models.” *Journal of Statistical Software* 91(2):1-40. 


### CSS Research Using Topic Models 
* DiMaggio, Paul, Manish Nag, and David Blei. 2013. “Exploiting Affinities between Topic Modeling and the Sociological Perspective on Culture: Application to Newspaper Coverage of U.S. Government Arts Funding.” *Poetics* 41(6): 570-606.
* Barberá, Pablo, Andreu Casas, Jonathan Nagler, Patrick J. Egan, Richard Bonneau, John T. Jost, and Joshua A. Tucker. 2019. “Who Leads? Who Follows? Measuring Issue Attention and Agenda Setting by Legislators and the Mass Public Using Social Media Data.” *American Political Science Review* 113(4): 883-901.
* Karell, Daniel and Michael Freedman. 2019. “Rhetorics of Radicalism.” *American Sociological Review* 84(4): 726-753.       
* Kennedy, I., C. Hess, A. Paullada, and S. Chasins. 2021. “Racialized Discourse in Seattle Rental Ad Text.” *Social Forces* 99(4): 1432–1456. 	   

## Chapter 5- Further Applications & Ethics

### Further Applications 

#### Word Embeddings
* Mikolov, Tomas, Kai Chen, Greg Corrado, and Jeffrey Dean. 2013. “Efficient Estimation of Word Representations in Vector Space.”  *Proceedings of Workshop at ICLR*: 1-22.
* Levy, Omer and Yoav Goldberg. 2014. “Neural Word Embedding as Implicit Matrix Factorization.” *Advances in Neural Information Processing Systems* 27: 1-9. 
* Garg, Nikhil, Londa Schiebinger, Dan Jurafsky, and James Zou. 2018. “Word Embeddings Quantify 100 years of Gender and Ethnic Stereotypes.” *Proceedings of the National Academy of Sciences* 115(16): E3635–E3644.
* Kozlowski, Austin C., Matt Taddy, and James A. Evans. 2019. “The Geometry of Culture: Analyzing the Meanings of Class Through Word Embeddings.” *American Sociological Review* 84(5): 905–949.
* Arseniev-Koehler, Alina and Jacob G. Foster. 2020. “Machine Learning as a Model for Cultural Learning: Teaching an Algorithm what it Means to be Fat.” Preprint, SocArXiv. 

#### Supervised NLP Classification Applied Studies
* Chenhao Tan, Vlad Niculae, Cristian Danescu-Niculescu-Mizil, and Lillian Lee. 2016. “Winning Arguments: Interaction Dynamics and Persuasion Strategies in Good-Faith Online Discussions,” *WWW*: 613–624.
* Davidson, Thomas, Dana Warmsley, Michael Macy, and Ingmar Weber. 2017. “Automated Hate Speech Detection and the Problem of Offensive Language.” *Proceedings of the 11th International Conference on Web and Social Media (ICWSM)*: 512–515. 
* Zhang, Justine, Jonathan P. Chang, Christian Danescu-Niculescu-Mizil, Lucas Dixon, Nithum Thain, Yiqing Hua, and Dario Taraborelli. 2018. “Conversations Gone Awry: Detecting Early Signs of Conversational Failure.”  *Proceedings of the 56th Annual Meeting of the Association for Computational Linguistics* 1: 1350-1361. 
* Barberá, Pablo, Amber E. Boydstun, Suzanna Linn, Ryan McMahon, and Jonathan Nagler. 2020. “Automated Text Classification of News Articles: A Practical Guide.” *Political Analysis*: 1–24


#### Networks 
* Gonzales-Bailon, Sanda, Andreas Kaltenbrunner, and Rafael E Banchs. 2010. “The Structure of Political Discussion Networks: A Model for the Analysis of Online Deliberation.” *Journal of Information Technology* 25: 230-243. 
* Rule, Alix, Jean-Phillippe Cointet, and Peter S. Bearman. 2015. “Lexical Shifts, Substantive Changes, and Continuity in State of the Union Discourse, 1790-2014.” *PNAS* 112(35): 10837-10844. 
* Bail, Christopher A. 2016. “Combining Natural Language Processing and Network Analysis to Examine How Advocacy Organizations Stimulate Conversation on Social Media.” *Proceedings of the National Academy of Sciences* 113(42): 11823-28.
* Vega, Davide and Matteo Magnani. 2018. “Foundations of Temporal Text Networks.” *Applied Network Science* 3(25): 1-26. 


#### Casual Inference
* Great GitHub repository of text & causality papers across disciplines-https://github.com/causaltext/causal-text-papers
* Bryan, Christopher J., Gregory M. Walton, Todd Rogers, and Carol S. Dweck. 2011. “Motivating Voter Turnout by Invoking the Self.” *PNAS* 108(31): 12653-12656. 
* Feder et al. 2021. “Causal Inference in Natural Language Processing: Estimation, Prediction, Interpretation and Beyond.” arXiv preprint arXiv: 2109.00725.
* Pryzant, Reid, Dallas Card, Dan Jurafsky, Victor Veitch, and Dhanya Sridhar. 2021. “Causal Effects of Linguistic Properties.” *Proceedings of the 2021 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies*: 4095-4109. 

### Ethics within NLP
Here’s a fantastic fairness within NLP Github repo from the UCLA NLP group that the following citations also draws from- https://github.com/uclanlp/awesome-fairness-papers

#### Broad Social Implications of NLP
* Hovy, Dirk and Shannon L. Spruit. 2016. “The Social Impact of Natural Language Processing.” *Proceedings of the 54th Annual Meeting of the Association for Computational Linguistics* 2: 591-598. 
* Blodgett, Su Lin, Solon Barocas, Hal Daum III, and Hanna Wallach. 2020. “Language (Technology) is Power: A Critical Survey of ‘Bias’ in NLP.” *Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics*: 5454-5476.
* Leins, Kobi, Jey Han Lau, and Timothy Baldwin. 2020. “Give Me Convenience and Give Her Death: Who Should Decide What Uses of NLP are Appropriate, and on What Basis?” *Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics*: 2908-2913. 

#### NLP’s Perpetuation of Bias and Unethical Practices
* Sap, Maarten, Dallas Card, Saadia Gabriel, Yejin Choi, and Noah A. Smith. 2019. “The Risk of Racial Bias in Hate Speech Detection.” *Proceedings of the 57th Annual Meeting of the Association for Computational Linguistics*: 1668-1678. 
* Gonen, Hila and Yoav Goldberg. 2019. “Lipstick on a Pig: Debiasing Methods Cover up Systematic Gender Biases in Word Embeddings But Do Not Remove Them.” *Proceedings of NAACL-HLT*: 609-614. 
* Hutchinson, Ben, Vinodkumar Prabhakaran, … et al. 2020. “Social Biases in NLP Models as Barriers for Persons with Disabilities.” *Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics*: 5491-5501. 
* Shmueli, Boaz, Jan Fell, Soumya Ray, and Lun-Wei Ku. 2021. “Beyond Fair Pay: Ethical Implications of NLP Crowdsourcing” *Proceedings of the 2021 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies*: 3758–3769
* Bender, Emily M., Timnit Gebru, Angelina McMillan-Major, and Shmargaret Smitchell. 2021. “On the Dangers of Stochastic Parrots: Can Language Models Be Too Big?” *Proceedings of the 2021 ACM Conference on Fairness, Accountability, and Transparency*: 610-623. 

#### NLP’s Revealing of Bias and Unethical Practices
* Voigt, Rob, Nicholas P Camp, … et al. 2017. “Language from Police Body Camera Footage Shows Racial Disparities in Officer Respect.” *PNAS* 114(25): 6521-6526. 
* Garg, Nikhil, Londa Schiebinger, Dan Jurafsky, and James Zou. 2018. “Word embeddings quantify 100 years of gender and ethnic stereotypes.” *Proceedings of the National Academy of Sciences 115* (16): E3635–E3644.
* Merullo, Jack, Luke Yeh, … et al. 2019. “Investigating Sports Commentator Bias Within a Large Corpus of American Football Broadcasts.” *Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing and the 9th International Joint Conference on Natural Language Processing*: 6355-6361. 
* Sap, Maarten, Saadia Gabriel, … et al. 2020. “Social Bias Frames: Reasoning about Social and Power Implications of Language.” *Proceedings of the 58th Annual Meeting of the Association for Computational Linguistics*: 5477-5490. 

#### Participant Privacy, Consent, and Agency
* Nissenbaum, Helen. 2004. “Privacy as Contextual Integrity.” *Washington Law Review*  79(1): 101-139. 
* Williams, Matthew L., Pete Burnap, and Luke Sloan. 2017. “Towards an Ethical Framework for Publishing Twitter Data in Social Research: Taking into Account Users’ Views, Online Context and Algorithmic Estimation.” *Sociology* 51(6): 1149-1168. 
* Susser, Daniel, Beate Roessler, and Helen Nissenbaum. 2019. “Technology, Autonomy, and Manipulation.” *Internet Policy Review* 8(2): 1-22. 
* Caselli, Tommaso, Roberto Cibin, … et al. 2021. “Guiding Principles for Participatory Design-Inspired Natural Language Processing.” *Proceedings of the 1st Workshop on NLP for Positive Impact*: 27-35. 

#### Incorporating Ethical Practices Within NLP
* Bender, Emily M. and Batya Friedman. 2018. “Data Statements for Natural Language Processing: Towards Mitigating System Bias and Enabling Better Science.” *Transactions of the Association for Computational Linguistics* 6: 587-604. 
* Jurgens, David, Eshwar Chandrasekharan, and Libby Hemphill. 2019. “A Just and Comprehensive Strategy for Using NLP to Address Online Abuse.” *Proceedings of the 57th Annual Meeting of the Association for Computational Linguistics*: 3658-3666. 
* Sun, Tony, Andrew Gaut… et al. 2019. “Mitigating Gender Bias in Natural Language Processing: Literature Review.” *Proceedings of the 57th Annual Meeting of the Association for Computational Linguistics*: 1630-1640. 
* Havens, Lucy, Melissa Terras, Benjamin Bach, and Beatrice Alex. 2020. “Situated Data, Situated Systems: A Methodology to Engage with Power Relations in Natural Language Processing Research.” *Proceedings of the Second Workshop on Gender Bias in Natural Language Processing*: 107-124. 




